# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
cat("running ", length(list.files(pattern="^t[0-9]+_.*\\.R$")), " tests\n", sep="")
files <- sort(list.files(pattern="^t[0-9]+_.*\\.R$"))
for (f in files) {
  cat("== ", f, " ==\n", sep="")
  source(f, local=TRUE)
}
