# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
n0 <- 4
n1 <- 4L
cat("typeof(n0)=", typeof(n0), " typeof(n1)=", typeof(n1), "\n", sep="")
cat("n0+1=", n0+1, " n1+1=", n1+1L, "\n", sep="")
