# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
x <- 3.9
cat("as.integer(x)=", as.integer(x), "\n", sep="")
cat("floor(x)=", floor(x), " ceiling(x)=", ceiling(x), "\n", sep="")
