# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
x <- c(-1, 0, 2, 2)
cat("x>0:", paste(x>0, collapse=" "), "\n", sep="")
cat("x==2:", paste(x==2, collapse=" "), "\n", sep="")
cat("any(x==2)=", any(x==2), " all(x> -2)=", all(x> -2), "\n", sep="")
