# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
a <- 1:5
b <- seq(0, 1, by=0.25)
cat("a:", paste(a, collapse=" "), "\n", sep="")
cat("b:", paste(b, collapse=" "), "\n", sep="")
