# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
x <- c(10, 20, 30)
cat("seq_len(5):", paste(seq_len(5), collapse=" "), "\n", sep="")
cat("seq_along(x):", paste(seq_along(x), collapse=" "), "\n", sep="")
