# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
x <- rep(1:3, times=2)
y <- rep(c(5,7), each=3)
cat("x:", paste(x, collapse=" "), "\n", sep="")
cat("y:", paste(y, collapse=" "), "\n", sep="")
