# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
x <- c(5, 9, 2, 8, 1)
cat("x[1]=", x[1], " x[5]=", x[5], "\n", sep="")
cat("x[2:4]:", paste(x[2:4], collapse=" "), "\n", sep="")
