# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
x <- 10:15
cat("drop2:", paste(x[-2], collapse=" "), "\n", sep="")
cat("drop2and4:", paste(x[c(-2,-4)], collapse=" "), "\n", sep="")
