# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
x <- c(-2, -1, 0, 1, 2)
sel <- x >= 0
cat("sel:", paste(sel, collapse=" "), "\n", sep="")
cat("x[sel]:", paste(x[sel], collapse=" "), "\n", sep="")
