# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
x <- c(5, 3, 5, 1)
cat("which(x==5):", paste(which(x==5), collapse=" "), "\n", sep="")
keys <- c(1, 5, 9)
cat("match(keys,x):", paste(match(keys, x), collapse=" "), "\n", sep="")
