# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
x <- c(1,2,3,4)
y <- c(2,2,2,2)
cat("x+y:", paste(x+y, collapse=" "), "\n", sep="")
cat("x*y:", paste(x*y, collapse=" "), "\n", sep="")
cat("x^2:", paste(x^2, collapse=" "), "\n", sep="")
