# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
x <- c(-1, 2, 0, 5)
y <- c( 3, 1, 0, 2)
cat("pmax:", paste(pmax(x,y), collapse=" "), "\n", sep="")
cat("pmin:", paste(pmin(x,y), collapse=" "), "\n", sep="")
