# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
x <- c(-3, -0.0, 2.5)
cat("abs:", paste(abs(x), collapse=" "), "\n", sep="")
cat("sign:", paste(sign(x), collapse=" "), "\n", sep="")
