# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
x <- c(1.2345, -1.2345)
cat("round2:", paste(round(x,2), collapse=" "), "\n", sep="")
cat("trunc:", paste(trunc(x), collapse=" "), "\n", sep="")
