# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
fmt <- function(x, d=12) {
  if (length(x) == 0) return("")
  paste(sprintf(paste0("%.", d, "f"), as.numeric(x)), collapse=" ")
}

x <- c(1, 2, 10)
cat("log:", fmt(log(x), 12), "\n", sep="")
cat("exp:", fmt(exp(c(0,1)), 12), "\n", sep="")
cat("sqrt:", fmt(sqrt(x), 12), "\n", sep="")
