# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
fmt <- function(x, d=12) {
  if (length(x) == 0) return("")
  paste(sprintf(paste0("%.", d, "f"), as.numeric(x)), collapse=" ")
}

x <- c(0, 0.5, 1.0)
cat("sin:", fmt(sin(x), 12), "\n", sep="")
cat("cos:", fmt(cos(x), 12), "\n", sep="")
