# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
i <- 0L
s <- 0L
repeat {
  i <- i + 1L
  if (i %% 2L == 0L) next
  s <- s + i
  if (i >= 9L) break
}
cat("s=", s, "\n", sep="")
