# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
m <- matrix(0, nrow=3, ncol=4)
for (i in 1:3) for (j in 1:4) m[i,j] <- 10*i + j
cat("m_row1:", paste(m[1,], collapse=" "), "\n", sep="")
cat("m_row3:", paste(m[3,], collapse=" "), "\n", sep="")
