# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
g <- function(x, a=2, b=1) a*x + b
cat("g(5)=", g(5), "\n", sep="")
cat("g(5,a=3,b=0)=", g(5, a=3, b=0), "\n", sep="")
