# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
h <- function(x) {
  y <- x
  y[2:length(y)] <- x[2:length(x)] - x[1:(length(x)-1)]
  y[1] <- x[1]
  y
}
x <- c(10, 13, 21, 22)
cat("h(x):", paste(h(x), collapse=" "), "\n", sep="")
