# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
fact <- function(n) {
  if (n <= 1) return(1L)
  p <- 1L
  for (i in 2:n) p <- p * i
  p
}
cat("fact(1)=", fact(1), " fact(6)=", fact(6), "\n", sep="")
