# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
x <- c(1, NA, 3, 4)
cat("sum_no_rm=", sum(x), "\n", sep="")
cat("sum_rm=", sum(x, na.rm=TRUE), "\n", sep="")
cat("mean_rm=", mean(x, na.rm=TRUE), "\n", sep="")
