# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
x <- c(1, NA, 3, NA, 5)
w <- which(is.na(x))
cat("which_na:", paste(w, collapse=" "), "\n", sep="")
x[is.na(x)] <- 0
cat("x:", paste(x, collapse=" "), "\n", sep="")
