# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
x <- c(3, 1, 2, 2)
cat("sort:", paste(sort(x), collapse=" "), "\n", sep="")
cat("order:", paste(order(x), collapse=" "), "\n", sep="")
