# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
x <- c(10, 5, 5, 20)
cat("rank_avg:", paste(rank(x, ties.method="average"), collapse=" "), "\n", sep="")
cat("rank_first:", paste(rank(x, ties.method="first"), collapse=" "), "\n", sep="")
