# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
x <- c(1,2,3,4)
cat("cumsum:", paste(cumsum(x), collapse=" "), "\n", sep="")
cat("cumprod:", paste(cumprod(x), collapse=" "), "\n", sep="")
cat("diff:", paste(diff(x), collapse=" "), "\n", sep="")
