# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
m1 <- matrix(1:6, nrow=2, ncol=3)
m2 <- matrix(1:6, nrow=2, ncol=3, byrow=TRUE)
cat("m1:", paste(as.vector(m1), collapse=" "), "\n", sep="")
cat("m2:", paste(as.vector(m2), collapse=" "), "\n", sep="")
