# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
m <- matrix(1:12, nrow=3, ncol=4)
cat("m[2,3]=", m[2,3], "\n", sep="")
cat("m[3,]:", paste(m[3,], collapse=" "), "\n", sep="")
cat("m[,2]:", paste(m[,2], collapse=" "), "\n", sep="")
