# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
m <- matrix(1:9, nrow=3, ncol=3)
d <- diag(m)
mt <- t(m)
cat("diag:", paste(d, collapse=" "), "\n", sep="")
cat("t_row1:", paste(mt[1,], collapse=" "), "\n", sep="")
