# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
a <- matrix(c(1,2,3,4), nrow=2)
b <- matrix(c(5,6,7,8), nrow=2)
c <- a %*% b
cat("c:", paste(as.vector(c), collapse=" "), "\n", sep="")
