# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
a <- matrix(1:6, nrow=2)
b <- matrix(rep(2,6), nrow=2)
cat("a_plus_b:", paste(as.vector(a+b), collapse=" "), "\n", sep="")
cat("a_times_b:", paste(as.vector(a*b), collapse=" "), "\n", sep="")
