# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
m <- matrix(1:12, nrow=3, ncol=4)
cat("rowsums:", paste(rowSums(m), collapse=" "), "\n", sep="")
cat("colsums:", paste(colSums(m), collapse=" "), "\n", sep="")
