# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
a <- matrix(c(2,1,1,3), nrow=2)
b <- c(1, 2)
x <- solve(a, b)
cat("x:", paste(sprintf("%.12f", x), collapse=" "), "\n", sep="")
