# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
x <- c(1,2,4,8,16)
q <- quantile(x, probs=c(0,0.25,0.5,0.75,1.0), type=1)
cat("q:", paste(q, collapse=" "), "\n", sep="")
