# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
s <- "hello"
t <- paste0(s, "_", 123)
cat("t=", t, "\n", sep="")
cat("substr=", substr(t, 1, 5), "\n", sep="")
cat("nchar=", nchar(t), "\n", sep="")
