# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
v <- c(a=10, b=20, c=30)
cat("names:", paste(names(v), collapse=" "), "\n", sep="")
cat("v['b']=", v["b"], "\n", sep="")
