# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
lst <- list(x=1:3, y=c(10,20))
cat("len=", length(lst), "\n", sep="")
cat("lst$x:", paste(lst$x, collapse=" "), "\n", sep="")
cat("lst[[2]]:", paste(lst[[2]], collapse=" "), "\n", sep="")
