# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
m <- matrix(1:12, nrow=3, ncol=4)
r <- apply(m, 1, sum)
c <- apply(m, 2, sum)
cat("apply_rows:", paste(r, collapse=" "), "\n", sep="")
cat("apply_cols:", paste(c, collapse=" "), "\n", sep="")
