# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
x <- 1:5
y <- c(2,1,0,-1,-2)
s1 <- sum(x*y)
s2 <- 0
for (i in 1:length(x)) s2 <- s2 + x[i]*y[i]
cat("s1=", s1, " s2=", s2, "\n", sep="")
