# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
lcg <- function(n, seed=1L) {
  a <- 1103515245L
  c <- 12345L
  m <- 2^31
  x <- integer(n)
  s <- seed
  for (i in 1:n) {
    s <- (a*s + c) %% m
    x[i] <- s
  }
  x
}
u32 <- lcg(5, seed=1L)
cat("u32:", paste(u32, collapse=" "), "\n", sep="")
u <- as.numeric(u32) / (2^31)
cat(sprintf("u: %.12f %.12f %.12f %.12f %.12f\n", u[1],u[2],u[3],u[4],u[5]))
