# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
lcg_u <- function(n, seed=7L) {
  a <- 1103515245L
  c <- 12345L
  m <- 2^31
  u <- numeric(n)
  s <- seed
  for (i in 1:n) {
    s <- (a*s + c) %% m
    u[i] <- as.numeric(s) / m
  }
  u
}
u <- lcg_u(1000, seed=7L)
cat(sprintf("mean=%.6f var=%.6f\n", mean(u), var(u)))
