# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
f <- function(x) x*x
a <- 0
b <- 1
n <- 1000L
h <- (b-a)/n
x <- a + h*(0:n)
y <- f(x)
trap <- h*(sum(y) - 0.5*(y[1] + y[length(y)]))
cat(sprintf("trap=%.8f\n", trap))
