# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
f <- function(x) x*x - 2
fp <- function(x) 2*x
x <- 1.0
for (i in 1:6) x <- x - f(x)/fp(x)
cat(sprintf("x=%.12f\n", x))
