# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
f <- function(x) x^3 - x - 2
a <- 1.0
b <- 2.0
for (i in 1:40) {
  m <- 0.5*(a+b)
  if (f(a)*f(m) <= 0) b <- m else a <- m
}
cat(sprintf("m=%.12f\n", 0.5*(a+b)))
