# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
x <- 1:5
y <- 2 + 3*x
xb <- mean(x); yb <- mean(y)
b1 <- sum((x-xb)*(y-yb))/sum((x-xb)^2)
b0 <- yb - b1*xb
cat(sprintf("b0=%.0f b1=%.0f\n", b0, b1))
