# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
coef <- c(1, -3, 2)  # 1 - 3x + 2x^2
x <- 5
y <- 0
for (i in length(coef):1) y <- y*x + coef[i]
cat("y=", y, "\n", sep="")
