# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
x <- c(1,2,3)
h <- c(1,1)
y <- numeric(length(x)+length(h)-1)
for (i in 1:length(x)) {
  for (j in 1:length(h)) {
    y[i+j-1] <- y[i+j-1] + x[i]*h[j]
  }
}
cat("y:", paste(y, collapse=" "), "\n", sep="")
