# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
f <- function(v) (v[1]-1)^2 + 2*(v[2]+2)^2
v <- c(0.5, -1.0)
eps <- 1e-6
g <- numeric(2)
for (i in 1:2) {
  vp <- v; vm <- v
  vp[i] <- vp[i] + eps
  vm[i] <- vm[i] - eps
  g[i] <- (f(vp) - f(vm))/(2*eps)
}
cat(sprintf("g=%.6f %.6f\n", g[1], g[2]))
