# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
f <- function(v) (v[1]-1)^2 + 2*(v[2]+2)^2
grad <- function(v) c(2*(v[1]-1), 4*(v[2]+2))
v <- c(10, 10)
alpha <- 0.1
for (i in 1:50) v <- v - alpha*grad(v)
cat(sprintf("v=%.6f %.6f f=%.6f\n", v[1], v[2], f(v)))
