# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
x <- 1:12
dim(x) <- c(3,4)
cat("x_dim:", paste(dim(x), collapse=" "), "\n", sep="")
cat("x_1_4=", x[1,4], "\n", sep="")
