# autogenerated R test case for partial R -> Fortran transpiler
options(digits=16)
m <- matrix(1:9, nrow=3)
v <- m[,2]
c <- m[,2, drop=FALSE]
cat("typeof_v=", typeof(v), " len_v=", length(v), "\n", sep="")
cat("dim_c:", paste(dim(c), collapse=" "), "\n", sep="")
