program main
implicit none
integer, parameter :: dp = kind(1.0d0)
real(kind=dp), parameter :: x = 1.0_dp
print*,abs(x)
print*,acos(x)
print*,acosh(x)
print*,asin(x)
print*,asinh(x)
print*,atan(x)
print*,atanh(0.5_dp)
print*,cos(x)
print*,cosh(x)
print*,exp(x)
print*,log10(x)
print*,sin(x)
print*,sinh(x)
print*,sqrt(x)
print*,tan(x)
print*,tanh(x)
print*,bessel_j0(x)
print*,bessel_j1(x)
print*,bessel_y0(x)
print*,bessel_y1(x)
print*,gamma(x)
print*,log_gamma(x)
print*,cosd(x)
print*,sind(x)
print*,tand(x)
print*,acosd(x)
print*,asind(x)
print*,spacing(x)
end
