import numpy as np

a = np.array([3.0, 1.0, 2.0, 2.0])
b = np.array([-1.0, 0.5, 4.0, 10.0])
c = np.array([1.0, 2.0, 3.0])
dv = np.array([4.0, 5.0, 6.0])
dm = np.array([[9.0, 8.0], [7.0, 6.0]])
rt = np.array([1.0, 2.0])

w = np.where(a > 1.5, a, b)
cl = np.clip(b, 0.0, 5.0)
cs = np.cumsum(a)
cp = np.cumprod(c)
mu = np.mean(a)
va = np.var(a)
sd = np.std(a)

e = np.eye(3)
i2 = np.identity(2)
d1 = np.diag(dv)
d2 = np.diag(dm)
rp = np.repeat(rt, 3)
tl = np.tile(rt, 3)
uq = np.unique(a)

print("where:", w)
print("clip:", cl)
print("cumsum:", cs)
print("cumprod:", cp)
print("mean:", mu)
print("var:", va)
print("std:", sd)
print("eye:")
print(e)
print("identity:")
print(i2)
print("diag_vec:")
print(d1)
print("diag_mat:", d2)
print("repeat:", rp)
print("tile:", tl)
print("unique:", uq)
